const sourceFile = new SourceMappedFile("../", undefined, "serverless.js")
const externalSource = sourceFile.addSource("framework.js", Framework.sourceCode)
const internalSource = sourceFile.addSource(methodData.stringName, methodData.content)
sourceFile.addSection(Framework.sourceCode, externalSource)
sourceFile.addSection(`\nFramework.initialize(${serialize(build)})`, internalSource)
return sourceFile.packAndMap()