const sourceFile = new SourceMappedFile("../", undefined, "service.js")
const externalSource = sourceFile.addSource("framework.js", Framework.sourceCode)
const internalSource = sourceFile.addSource(property.filename, property.content)
sourceFile.addSection(Framework.sourceCode, externalSource)
sourceFile.addSection(`\nFramework.initialize(${serialize(build)})`, internalSource)
return sourceFile.packAndMap()