return `<p>An incredible combinatorial explosion appears when you try to compute the number of unique URLs that can exist. The purpose of this note is not to compute the actual number, but to give you a tiny hint at how unfathomably large that number might be. There are far, far, far more possible URLs than there are <a ${_.pointAttr} href=${notes[1762062190].canonicalURL}>particles in the known universe</a>. To determine the actual cardinality we'd need to settle a few questions. For example, are consecutive slashes allowed or will they be normalized away? Do we limit ourselves to <a ${_.pointAttr()} href="https://support.microsoft.com/en-us/topic/maximum-url-length-is-2-083-characters-in-internet-explorer-174e7c8a-6666-f4e0-6fd6-908b53c12246#:~:text=Microsoft%20Internet%20Explorer%20has%20a,request%20and%20GET%20request%20URLs." class="external">two thousand characters like Internet Explorer</a> or <a ${_.pointAttr()} href="https://chromium.googlesource.com/chromium/src/+/main/docs/security/url_display_guidelines/url_display_guidelines.md#:~:text=Chrome%20limits%20URLs%20to%20a,is%20used%20on%20VR%20platforms." class="external">two million like Chrome</a>? In this note, I've gone factor-by-factor and, at each step, I've chosen the worst possible case and reduced the set down into one whose size we can compute with a simple exponent.</p>
<h2>Worst-Case Length</h2>
<p>We start by limiting ourselves to the worst possible length. Early browsers could only handle URLs up to 2000 characters. Since modern browsers like Chrome can support much more, we just removed 99.9% of the URLs from the "modern" set. There's still a lot of nuance to computing the cardinality of the remaining 0.1%.</p>
<h2>No Protocol Mutability</h2>
<p>There are many different <a ${_.pointAttr()} href="https://datatracker.ietf.org/doc/html/rfc3986#section-3.1" class="external">schemes and protocols</a> that a valid URL can have. Forget about any cardinality imparted by that. We will only talk about "https://". This leaves us with only a fraction of the true set, and we can go ahead and subtract the 8 characters in "https://" from our 2000 character limit, leaving us with 1992 variable characters.</p>
<h2>Worst Possible Host</h2>
<p>What about the host name? The number of possible domain names is, by itself, vastly larger than the number of particles in the known universe, but for the sake of this note we'll pick only one and make it the worst possible one. The maximum length of a domain name (including dots) is 255 characters. We will limit our set to only those URLs that use the following domain name:</p>
<pre>heres.a.huge.domain.name.as.long.as.it.can.possibly.be.abcdefghijklmnopqrstuvwxyz.abcdefghijklmnopqrstuvwxyz.abcdefghijklmnopqrstuvwxyz.abcdefghijklmnopqrstuvwxyz.abcdefghijklmnopqrstuvwxyz.abcdefghijklmnopqrstuvwxyz.abcdefghijklmnopqrstuvwxyz.example.com</pre>
<p>We just removed pretty much all URLs from the set except the miniscule fraction that include this domain name. It takes up 255 characters of our 1992 characters, leaving 1737 characters.</p>
<h2>No Optional Features</h2>
<p>There's still a lot of unpredictability in what those 1737 characters might be. For example, we could include <a ${_.pointAttr()} href="https://datatracker.ietf.org/doc/html/rfc3986#section-3.2.1" class="external">user credentials</a> (a universe of its own), a specific <a ${_.pointAttr()} href="https://datatracker.ietf.org/doc/html/rfc3986#section-3.2.3" class="external">port</a> (a number between 0 and 65,535), an untold variety of <a ${_.pointAttr()} href="https://datatracker.ietf.org/doc/html/rfc3986#section-3.4" class="external">query parameters</a>, and a whole universe of possible <a ${_.pointAttr()} href="https://datatracker.ietf.org/doc/html/rfc3986#section-3.5" class="external">hash fragments</a>, all of which multiply by each other to increase the size of the set, but they also add an incredible amount of complexity to the equation.</p>
<p>Luckily, they're all optional. Let's just remove them from consideration for today, and only include URLs that have none of these features. We just removed virtually all of the URLs we still had left.</p>
<h2>No Variable-length Pathnames</h2>
<p>At this point, we're really just counting the set of all valid <a ${_.pointAttr()} href="https://datatracker.ietf.org/doc/html/rfc3986#section-3.3" class="external">pathnames</a> up to 1737 characters long. Pathnames require at least the initial slash and the empty pathname without an initial slash will resolve to one with it or vice versa. So, we'll just throw away that first pathname character as it can't be anything other than a slash.</p>
<p>There are <a ${_.pointAttr()} href=${notes[1762157702].canonicalURL}>more variable-length pathnames than fixed length ones of some length <math><mi>n</mi></math></a>. To find out how many, we'd add that single slash pathname to the number of 2-character pathnames to the number of 3-character ones and so on. To compute that, we require at least a <a ${_.pointAttr()} href="https://en.wikipedia.org/wiki/Geometric_series" class="external">geometric series</a>. That's too rich for our worst-case set, so let's just remove every URL whose pathname is not exactly 1737 characters long. We just removed almost every URL we have in our already stripped-down set.</p>
<h2>No Special Characters</h2>
<p>Modern browsers support 85+ characters in the URL pathname (once you include the percent symbol, comma, parenthesis, square brackets, period, exclamation point, etc.), suggesting it might be possible to approach base 85.</p>
<p>There's just one problem: a lot of these special symbol combinations will get stripped away/normalized down to others during URL resolution. Some will be treated inconsistently in platforms that let you embed links. Others will cause an error if used incorrectly. It isn't trivial to compute the cardinality of that.</p>
<p>The solution? You guessed it. We'll remove most of the URLs from our set! Let's only consider URLs that use the following 64 character alphabet to spell out their pathname segments:</p>
<pre>abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-_</pre>
<p>But we can't just string together 1737 of these bad boys and call it a day…</p>
<h2>No Variable-length Segments</h2>
<p>A valid URL pathname can be broken up into segments, each separated by a forward slash. Some systems throw an error if even one of those segments is longer than 250 characters. It wouldn't be terribly hard to account for these arrangements but it <em>would</em> mean writing out a geometric series. So, let's only count URLs that have this exact arrangement: seven fixed-length segments (six 250-character segments followed by one 230 character segment). This requires seven slashes to split it all up; 1737 minus 7 leaves us with an even 1730 segment characters that can actually change between URLs.</p>
<p>Not to sound like a broken record, but almost none of the URLs in our already tiny set had this exact arrangement. We just removed almost everything we had left, yet again.</p>
<p>Just for fun, here is a "random" (but valid) URL from our set:</p>
<pre>https://heres.a.huge.domain.name.as.long.as.it.can.possibly.be.abcdefghijklmnopqrstuvwxyz.abcdefghijklmnopqrstuvwxyz.abcdefghijklmnopqrstuvwxyz.abcdefghijklmnopqrstuvwxyz.abcdefghijklmnopqrstuvwxyz.abcdefghijklmnopqrstuvwxyz.abcdefghijklmnopqrstuvwxyz.example.com/ld9370LC9uzp83Mklv90dujd9v7774n0V7p7em5078B7S790dkb094977au9D07B098yAV76ouyf79J7uft7d5f77g90jki98765dc7hkji7865d7dgy77yuhjkIk8Kgf567hj9ny7GVNjn7677V9jbvr567bj099efbn49efg776ft5x4rxi7T8Yoih0n7hv6r4d657d8g9u8b779ub8yf7t7d75d674s77743s2a1a7772zqzdtcuhbi/007opkolpp7m777ko7n777ou77h8yvtcr7tds5es5241awzsx7dfchvj7jkhboi78g8765c6e4x421s576y57t6fv8iub9ub87ytvc64dc768fv897b9ub9yv7tc7tv8ybhvutF64d52as2zfxcghvbhininIonoi0ih9ubgiI0P1MS07vmllp0097f74d2wa1asswextyvunimlljo00987643212wzqz1a12aswzz23sxerc34dfcrvr/5fvtby65g67buh7nu98m09k0,00k9jubyuhubvtctvubuvtdcrd4dxw23314152375786e6d976f70867f97743d8742a13s7278rf97vtiyfcdtd7xtrwSte7wrxztewzyrTUCtivuyvbOUyv77utrs462s67546rv9vbyv8rtc6X4s13A2ezwrexrcYdexwa2WESDfgtyu789iujhnmko9iujhbVFdre321qasxcfvghuiuytr432was/zxcvfghyui9o876543wsaxcdfghyuI9Oijnjiuygtftdrezwertrytfugyhiu8978gtf7r6d53s64512zwxetCRYtfughioYG87f564dsetrcyvubhij9i8u7t6f5r7743217aqwezsxdcrft7gyh77ujikJHgt5432177777qwertyhj7kJHgre321qaszxcvghjio987654321QWErfcv7bhuyTRfdfgtyui987654321qwerfv77798/bnhjHGv7fghjio09oiujhn7b7VCxsaq12we7rty7u8Ikj7hgFD777seRTyu876YT7r4ewsDFghJiuy6543721Qas7zxcVBnjio9876574321qasDFGhbnJUytrfdsERtyuJHgbvfdeRthBVGCFdsw34543212qaszxcVbghjkio0987654321qasZXcvbnhJKo0987654ERD7sw21qas7ZXcfghyuI9O0okmjki87uyhgbvgt54edsxzsa/Q12qwasXCfrt56tygBnhjio909OIKjmnko09iujhY76tfgcder321q7aszxCvgbhjui7uY6T5r4e321234567879i8UytrfdsXcvbghjIuyTRewqA7SzxcvbgHJik7oKjmjI7UyhgfrEwszx7sAWaszxcdftYUijkmjNHBGfrtYuiuYTredFCghyui89876543eDfgyuytr43edfgyuhbghJUI987654321qaszxCVghui9o876543wErt/fGHYBUtcu63s312asydu6IYUTYVbokuvhtExt42at4wrexcutyvbo8ygoiyrc53yr3254Sdu6rfvoyboiybiutyvyuCtycurc6u5c865777ctycuyut7ityd7i6757DE7U7674s5u74s54sd7xry7txc7jyrfxd7j7yrDujdI7775edu77564st427as13szr7ezUT7rxiYGCkyuC77FJut7ykm79OM0p7978t</pre>
<p>It's exactly 2000 characters long. It has the same impossibly unlikely domain name as every other URL in our set, and an incredibly unlikely sequence of pathnames. I mashed my keyboard as fast as I could and didn't bother adding any underscores or dashes, and it still took a surprisingly long time to type this out. That gives you some idea of just how many different URLs of this limited form exist.</p>
<h2>Final Cardinality of our Set</h2>
<p>Our set should be a truly miniscule fraction of a fraction of a fraction of a fraction of a fraction of a fraction of a fraction of the set of valid URLs that can exist. Ultimately, what we've got here isn't even a drop in the bucket compared to the set of all possible URLs. But the good news is we finally have a set that can be represented by a trivial cardinality expression: <math><mi>k</mi><mo>=</mo><msup><mn>64</mn><mn>1730</mn></msup></math></p>
<p>There are less than <math><msup><mn>64</mn><mn>54</mn></msup></math> particles in the known universe, which we can round to this:</p>
<pre>1000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000</pre>
<p>Contrast that with <math><msup><mn>64</mn><mn>1730</mn></msup></math>. The ratio of <math><msup><mn>64</mn><mn>54</mn></msup></math> to <math><msup><mn>64</mn><mn>1730</mn></msup></math> is basically 0:1. But what does <math><msup><mn>64</mn><mn>1730</mn></msup></math> look like? See for yourself:</p>
<pre>${64n ** 1730n}</pre>
<p>That's a lot of URLs.</p>
<h2>Conclusion</h2>
<p>Thanks for reading. I realize that knowing the size of this incredibly tiny and useless set of URLs isn't as satisfying as knowing the actual number of valid URLs. Computing that number would be a massive undertaking and require more assumptions and math than I'm prepared to do in this humble notebook. Still, I hope the ones we did count gives you some idea of how stupendously large the real number must be. The number of possible URLs tells us the amount of information content that any given URL carries. The URLs in our set carry 1730 <a ${_.pointAttr()} href=${notes[1753817767].canonicalURL}>charms</a> of information, equivalent to roughly 10,380 bits or 1.3 kilobytes.</p>`