scroller.container = document.querySelector(scroller.query + ">scroller-")
scroller.scrollBar = document.querySelector(scroller.query + ">scroll-bar")
scroller.content = document.querySelector(scroller.query + ">scroller->scroll-content")
scroller.container.addEventListener("scroll", scroller.listener, { passive: true })
scroller.observer = new ResizeObserver(() => scroller.onresize())
scroller.observer.observe(scroller.content)